export enum ProjectStatus {
  PLANNED = 'PLANNED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  ARCHIVED = 'ARCHIVED',
}

export enum BudgetType {
  NONE = 'NONE',
  CAPPED = 'CAPPED',
  TRACKED_ONLY = 'TRACKED_ONLY',
}

export enum TaskStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  DONE = 'DONE',
  CANCELLED = 'CANCELLED',
}

export enum TaskType {
  ARCHITECTURE_ENGINEERING_DIRECTION = 'ARCHITECTURE_ENGINEERING_DIRECTION',
  DESIGN_DELIVERY_RESEARCH = 'DESIGN_DELIVERY_RESEARCH',
  DEVELOPMENT_TESTING = 'DEVELOPMENT_TESTING',
  BUSINESS_SUPPORT = 'BUSINESS_SUPPORT',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
}
